#!/usr/bin/env bash
# 月更提醒：上游 Kristal main 有新提交 → 开一条提醒 issue 做月度适配更新。
#
# 为什么判据是【提交】不是版本号（AIk 2026-09-21 定）：
#   上游是滚动开发，VERSION 文件长期恒为 0.11.0-dev —— 拿版本号比较等于比一个恒量，
#   永远"一致"，那套信号是死的。**只要提交动了就是更新。**
#
# 环境变量:
#   UPSTREAM_REPO / UPSTREAM_BRANCH / UPSTREAM_FILE（默认 KristalTeam/Kristal main VERSION）
#
# 行为（每次运行）:
#   1. **已有 open 的 [update] issue → 直接跳过**（AIk 2026-09-21 定：还挂着的那条就是提醒本身，
#      不重复触发；他处理完自己关掉后，下个月才重新提醒）
#   2. 取上游 main HEAD 的 sha / 日期 / VERSION
#   3. 锚点 = 最近一条已关闭的 [update] issue 的关闭时间（= 他上次同步完的时间）；没有则取 30 天前
#   4. 统计上游自锚点以来的提交：有 → create issue（标题带 YYYY-MM + 新增提交数，正文列最近 10 条）；
#      没有 → 静默退出（上游没动，不打扰）
#   5. **不自动关闭 issue** —— 适配更新完由 AIk 手动关；下个月从他关闭的时间起算。
set -euo pipefail

UPSTREAM_REPO="${UPSTREAM_REPO:-KristalTeam/Kristal}"
UPSTREAM_BRANCH="${UPSTREAM_BRANCH:-main}"
UPSTREAM_FILE="${UPSTREAM_FILE:-VERSION}"
PREFIX="[update]"
REPO="${GITHUB_REPOSITORY:-Bli-AIk/unknown}"

CI_NOTE_EN="Generated by CI: monthly reminder on the 18th at 01:30 UTC (09:30 UTC+8); manual dispatch available."
CI_NOTE_ZH="本提醒由 CI 自动生成：每月 18 号 01:30 UTC（东八 09:30）月更提醒；可手动触发。"

log() { echo "[$(date -u +%FT%TZ)] $*"; }

# 新建提醒 issue（不在已有 issue 上做 edit —— 有 open 就直接跳过，见 main）
create_issue() {
  local title="$1" body="$2" url
  url="$(gh issue create --title "$title" --body "$body" 2>/dev/null || true)"
  log "已新建 issue ${url:-（创建可能失败，看日志）}"
}

main() {
  local head_sha head_short head_date upstream_ver month anchor commits count list body open_nums

  # 已有 open 的 [update] issue → 不重复提醒（他自己关掉后，下个月才重新触发）
  open_nums="$(gh issue list --state open --limit 100 --json number,title \
    --jq '[.[] | select(.title | startswith("[update]")) | .number] | join(",")' 2>/dev/null || true)"
  if [[ -n "$open_nums" ]]; then
    log "已有 open $PREFIX issue（#${open_nums}）→ 本次不提醒；处理完关闭后，下个月才重新触发"
    return
  fi

  head_sha="$(gh api "repos/${UPSTREAM_REPO}/commits/${UPSTREAM_BRANCH}" --jq '.sha')"
  head_short="${head_sha:0:7}"
  head_date="$(gh api "repos/${UPSTREAM_REPO}/commits/${UPSTREAM_BRANCH}" --jq '.commit.committer.date[0:10]')"
  upstream_ver="$(gh api "repos/${UPSTREAM_REPO}/contents/${UPSTREAM_FILE}?ref=${UPSTREAM_BRANCH}" --jq '.content' 2>/dev/null \
    | base64 -d 2>/dev/null | tr -d '[:space:]' || true)"
  month="$(date -u +%Y-%m)"

  anchor="$(gh issue list --state closed --limit 100 --json title,closedAt \
      --jq '[.[] | select(.title | startswith("[update]"))] | sort_by(.closedAt) | reverse | .[0].closedAt // empty' 2>/dev/null || true)"
  if [[ -z "$anchor" ]]; then
    anchor="$(date -u -d '30 days ago' +%FT%TZ)"
    log "无历史已关闭 $PREFIX issue → 锚点取 30 天前：${anchor}"
  fi

  commits="$(gh api "repos/${UPSTREAM_REPO}/commits?sha=${UPSTREAM_BRANCH}&since=${anchor}&per_page=100" 2>/dev/null || echo '[]')"
  count="$(printf '%s' "$commits" | jq 'length')"

  log "repo=${REPO} upstream=${head_short} since=${anchor} 新增提交=${count}"

  if [[ "$count" -eq 0 ]]; then
    log "上游自 ${anchor} 以来没有新提交 → 静默（不打扰）"
    return
  fi

  list="$(printf '%s' "$commits" | jq -r '.[0:10][] | "- \(.sha[0:7]) — \(.commit.committer.date[0:10]) \(.commit.message | split("\n")[0])"')"

  body="**Monthly Update Reminder**

- Upstream ${UPSTREAM_REPO}@${UPSTREAM_BRANCH}: ${head_short} (${head_date}), VERSION ${upstream_ver}
- New commits since your last sync (${anchor}): **${count}**

Latest commits:

${list}

Adapt this repo to upstream, then **close this issue yourself** — next month's count starts from your close time. This issue is never auto-closed, and while it stays open no further reminder is created.

${CI_NOTE_EN}

---

**月更提醒**

- 上游 ${UPSTREAM_REPO}@${UPSTREAM_BRANCH}：${head_short}（${head_date}），VERSION ${upstream_ver}
- 自你上次同步（${anchor}）以来，上游新增 **${count}** 个提交

最近几条：

${list}

把本仓库适配到上游，完成后**自己关掉本 issue**（本 workflow 不会自动关它，只要它开着就不会再生成新的提醒）—— 下个月的计数从你关闭的时间起算。

${CI_NOTE_ZH}"

  create_issue "${PREFIX} ${month} monthly: ${count} new upstream commits (${head_short})" "$body"
}

main
