-- Library globals, generated by tools/gen-lib-globals.sh. Do not edit by hand.
--
-- These names are not defined by this mod: each library registers them as
-- real Lua globals at runtime (Registry.registerGlobal, or a scripts/globals
-- script whose return value the Registry publishes), so mod code can use them
-- bare, matching the Kristal library semantics. This file only teaches LuaLS
-- about those globals; each require is path-style so LuaLS resolves it
-- straight to the library source file.

---@diagnostic disable-next-line: undefined-global
AUTO_LANGUAGE = require("libraries/kristal-i18n/lib")

---@diagnostic disable-next-line: undefined-global
CJK_DIALOGUE_TEXT_SPACING = require("libraries/kristal-i18n/lib")

---@diagnostic disable-next-line: undefined-global
CJK_DIALOGUE_Y_OFFSET = require("libraries/kristal-i18n/lib")

---@diagnostic disable-next-line: undefined-global
CJK_FIXED_TEXT_SPACING = require("libraries/kristal-i18n/lib")

---@diagnostic disable-next-line: undefined-global
CJK_TYPEWRITER_SPEED_MULTIPLIER = require("libraries/kristal-i18n/lib")

---@diagnostic disable-next-line: undefined-global
DEFAULT_LANGUAGE = require("libraries/kristal-i18n/lib")

---@diagnostic disable-next-line: undefined-global
DEFAULT_LANGUAGE_TOGGLE_KEY = require("libraries/kristal-i18n/lib")

---@diagnostic disable-next-line: undefined-global
FALLBACK_LANGUAGE = require("libraries/kristal-i18n/lib")

---@diagnostic disable-next-line: undefined-global
ID_INTERP_PATTERN = require("libraries/kristal-i18n/lib")

---@diagnostic disable-next-line: undefined-global
KristalDebugTools = require("libraries/kristal-debug-tools/lib")

---@diagnostic disable-next-line: undefined-global
LightActionBox = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/UI/LightActionBox.lua")

---@diagnostic disable-next-line: undefined-global
LightActionButton = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/UI/LightActionButton.lua")

---@diagnostic disable-next-line: undefined-global
LightArena = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/LightArena.lua")

---@diagnostic disable-next-line: undefined-global
LightArenaSprite = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/LightArenaSprite.lua")

---@diagnostic disable-next-line: undefined-global
LightAttackBar = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/UI/LightAttackBar.lua")

---@diagnostic disable-next-line: undefined-global
LightAttackBox = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/UI/LightAttackBox.lua")

---@diagnostic disable-next-line: undefined-global
LIGHT_BATTLE_LAYERS = require("libraries/MagicalGlassRedux/lib")

---@diagnostic disable-next-line: undefined-global
LightBattle = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle.lua")

---@diagnostic disable-next-line: undefined-global
LightBattleUI = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/UI/LightBattleUI.lua")

---@diagnostic disable-next-line: undefined-global
LightBullet = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/LightBullet.lua")

---@diagnostic disable-next-line: undefined-global
LightDamageNumber = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/UI/LightDamageNumber.lua")

---@diagnostic disable-next-line: undefined-global
LightEncounter = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/LightEncounter.lua")

---@diagnostic disable-next-line: undefined-global
LightEnemyBattler = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/LightEnemyBattler.lua")

---@diagnostic disable-next-line: undefined-global
LightEnemySprite = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/LightEnemySprite.lua")

---@diagnostic disable-next-line: undefined-global
LightGauge = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/UI/LightGauge.lua")

---@diagnostic disable-next-line: undefined-global
LightHelpWindow = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/UI/LightHelpWindow.lua")

---@diagnostic disable-next-line: undefined-global
LightPartyBattler = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/LightPartyBattler.lua")

---@diagnostic disable-next-line: undefined-global
LightRecruit = require("libraries/MagicalGlassRedux/scripts/globals/LightRecruit.lua")

---@diagnostic disable-next-line: undefined-global
LIGHT_SHOP_LAYERS = require("libraries/MagicalGlassRedux/lib")

---@diagnostic disable-next-line: undefined-global
LightShop = require("libraries/MagicalGlassRedux/scripts/globals/LightShop.lua")

---@diagnostic disable-next-line: undefined-global
LightSoul = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/LightSoul.lua")

---@diagnostic disable-next-line: undefined-global
LightSpeechBubble = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/UI/LightSpeechBubble.lua")

---@diagnostic disable-next-line: undefined-global
LightStatusDisplay = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/UI/LightStatusDisplay.lua")

---@diagnostic disable-next-line: undefined-global
LightTensionBarGlow = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/UI/LightTensionBarGlow.lua")

---@diagnostic disable-next-line: undefined-global
LightTensionBar = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/UI/LightTensionBar.lua")

---@diagnostic disable-next-line: undefined-global
LightWave = require("libraries/MagicalGlassRedux/scripts/globals/LightBattle/LightWave.lua")

---@diagnostic disable-next-line: undefined-global
MG_EVENT = require("libraries/MagicalGlassRedux/lib")

---@diagnostic disable-next-line: undefined-global
MG_GAMEOVERS = require("libraries/MagicalGlassRedux/lib")

---@diagnostic disable-next-line: undefined-global
MG_PALETTE = require("libraries/MagicalGlassRedux/lib")

---@diagnostic disable-next-line: undefined-global
ObjectEditor = require("libraries/kristal-object-selector-plus/lib")

---@diagnostic disable-next-line: undefined-global
RandomEncounter = require("libraries/MagicalGlassRedux/scripts/globals/RandomEncounter.lua")

---@diagnostic disable-next-line: undefined-global
VirtualKeyboard = require("libraries/virtualkeyboard/lib")
