-- Library globals, generated by tools/gen-lib-globals.sh. Do not edit by hand.
--
-- These names are not defined by this mod: each library registers them as
-- real Lua globals at runtime (Registry.registerGlobal, or a scripts/globals
-- script whose return value the Registry publishes), so mod code can use them
-- bare, matching the Kristal library semantics. This file only teaches LuaLS
-- about those globals; each require is path-style so LuaLS resolves it
-- straight to the library source file.

---@diagnostic disable-next-line: undefined-global
KristalDebugTools = require("libraries/kristal-debug-tools/lib")

---@diagnostic disable-next-line: undefined-global
ObjectEditor = require("libraries/kristal-object-selector-plus/lib")

---@diagnostic disable-next-line: undefined-global
VirtualKeyboard = require("libraries/virtualkeyboard/lib")
